{
  config,
  lib,
  modulesPath,
  disko,
  nixos-private,
  ...
}:

let
  cfg = config.profiles.machines.vm;
in
{
  imports = [
    disko.nixosModules.disko
    (modulesPath + "/profiles/qemu-guest.nix")
    ../../server
  ];

  options.profiles.machines.vm = {
    enable = lib.mkEnableOption "shared QEMU VM configuration";

    address = lib.mkOption {
      type = lib.types.str;
      example = "192.168.0.10";
      description = "Static IPv4 address for eth0.";
    };

    gateway = lib.mkOption {
      type = lib.types.str;
      default = "192.168.0.1";
      description = "IPv4 Gateway address for eth0";
    };

    diskSize = lib.mkOption {
      type = lib.types.str;
      default = "40GiB";
      description = "Size of the VM disk image generated by disko.";
    };
  };

  config = lib.mkIf cfg.enable {
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

    boot.kernelParams = [ "net.ifnames=0" ];

    services.qemuGuest.enable = true;

    services.beszel.agent = {
      enable = true;
      environmentFile = config.age.secrets.beszel-agent-env.path;
    };

    networking = {
      useDHCP = false;
      defaultGateway = cfg.gateway;
      firewall.enable = true;

      interfaces.eth0 = {
        useDHCP = false;
        ipv4.addresses = [
          {
            address = cfg.address;
            prefixLength = 24;
          }
        ];
      };
    };

    services.openssh.settings.PermitRootLogin = lib.mkForce "yes";

    users.users = {
      root.openssh.authorizedKeys.keys = [
        nixos-private.private.keys.personal.ssh.pub
      ];

      dewaldv.openssh.authorizedKeys.keys = [
        nixos-private.private.keys.personal.ssh.pub
      ];
    };

    disko.devices.disk.main = {
      device = "/dev/sda";
      imageSize = cfg.diskSize;
      type = "disk";
      content = {
        type = "gpt";
        partitions = {
          ESP = {
            label = "ESP";
            type = "EF00";
            size = "512M";
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
              mountOptions = [ "umask=0077" ];
            };
          };

          root = {
            label = "nixos";
            size = "100%";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
            };
          };
        };
      };
    };
  };
}
